### ISSUE TITLE
graag ook de bestanden hier

### ISSUE THREAD

**Issue by Theo-denBlanken** [pimhakkert/Album-cover-site#1]
Je hebt feedback gekregen van **Theo-denBlanken**
URL: https://github.com/pimhakkert/Album-cover-site/blob/master/

Feedback: daar gaat het in GitHub om[](http://www.studiozoetekauw.nl/codereview-in-het-onderwijs/ '#cr:{"reviewer":"Theo-denBlanken"}')

**Comment by pimhakkert** [comment]
Documenten toegevoegd.
