### ISSUE TITLE
Er is blijkbaar geen overflow: hidden

### ISSUE THREAD

**Issue by Theo-denBlanken** [pimhakkert/Album-cover-site#2]
Je hebt feedback gekregen van **Theo-denBlanken**
URL: https://github.com/pimhakkert/Album-cover-site/blob/master/

Feedback: want je ziet de articles invliegen[](http://www.studiozoetekauw.nl/codereview-in-het-onderwijs/ '#cr:{"reviewer":"Theo-denBlanken"}')

**Comment by pimhakkert** [comment]
Gefixed.
